dist: bionic
os:
  - linux
  - osx

language: rust
cache: cargo
rust:
  - nightly

env:
  global:
    - RUST_BACKTRACE=1

# Always test things that aren't pushes (like PRs)
# or test master or test tagged releases on push (with versioning)
if: type != push OR branch = master OR branch =~ /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

matrix:
  include:
    - name: "lint"
      os: linux
      rust: nightly
      before_script:
        - rustup component add rustfmt --toolchain nightly;
        - rustup component add clippy --toolchain=nightly || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      script:
        - cargo fmt -- --check;
        - cargo clippy --all-targets --all-features -- -D clippy::all -D clippy::pedantic

